# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/scholarship_db
spring.datasource.username=postgres
spring.datasource.password=CodeDifferently261!

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Grants.gov (no API key required)
grants.gov.url=https://api.grants.gov/v1/api/search2